Repository thoth-station/solver-error-classfier, pull requests merged in 2021-12, with the labels that each got.

#25 Add and update Thoth GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/kebechet_info.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, size/M, lgtm

#28 Update pyproject.toml to use Python 3.8
  pyproject.toml
Labels: approved, size/XS

#29 fixed import error
  app.py
  version.py
Labels: approved, size/S

#39 fixed pipfile and setup.py
  Pipfile
  setup.py
Labels: approved, size/XS

#45 Added app.sh script
  app.py
  app.sh
Labels: approved, size/S

#51 Added version.py
  app.sh
  classify.py
  version.py
Labels: approved, size/S

#53 fixed setup.py
  setup.py
Labels: approved, size/XS
